export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  PACKAGE_NOT_PUBLISHED: 'PACKAGE_NOT_PUBLISHED',
  INVENTORY_UNAVAILABLE: 'INVENTORY_UNAVAILABLE',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  DESTINATION_NOT_FOUND: 'DESTINATION_NOT_FOUND',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
} as const;
